spring:
  application:
    name: musinsa-homework
  datasource:
    url: jdbc:mysql://localhost:3306/musinsa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

elasticsearch:
  host: localhost
  port: 9200